# available directory themes:
# spearmint, peppermint, hemingway, brookmint
theme = 'brookmint'

[general]
title = "Directory"
logo = ""
iconLogo = "tabler:grid-dots"

[general.seo]
name = "Directory"
description = "A clean directory for your entities."
url = "https://yourdomain.com"

[directoryData.source]
name = "json"    # default, mock, sheets, json
links = "normal"
linksOutbound = false

[directoryData.tagPages]
title = "{0} Items"

[directoryData.search]
placeholder = "Search among {0} listings"

[[directoryData.tags]]
key = "example"
name = "Example"
color = "blue"
emoji = "📝"
description = "Example category for demonstration."

[header.banner]
show = false
text = ""
link = ""
brandText = ""

[header.navbar]
colorModeSelector = false

[[header.navbar.links]]
name = "Blog"
href = "/blog"

[header.actionButton]
text = "Submit"
href = "#"

[footer]
description = "A clean directory for your entities."

[footer.socials.x]
link = "https://x.com/yourusername"

[footer.socials.youtube]
link = "https://www.youtube.com/@yourchannel"